using Microsoft.VisualBasic;
using SNR_ClientApp.Properties;
using SNR_ClientApp.TallyResponses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SNR_ClientApp.Tally.generateXml
{
	internal class CompanyStockItemXml
	{
		public ENVELOPE getCompanyStockItemXml()
		{
			ENVELOPE tallyRequest = new ENVELOPE();
			HEADER header = new HEADER();
			header.VERSION = "1";
			header.TALLYREQUEST = "Export";
			header.TYPE = "Collection";
			header.ID = "Collection of Stock Items";
			tallyRequest.HEADER = header;
			BODY body = new();
			DESC desc = new();
			STATICVARIABLES staticvariables = new STATICVARIABLES();
			staticvariables.EXPLODEFLAG = "Yes";
			staticvariables.SVCURRENTCOMPANY = ApplicationProperties.properties["tally.company"].ToString();
			staticvariables.SVEXPORTFORMAT = "$$SysName:XML";
			staticvariables.IsItemWise = "Yes";
			desc.STATICVARIABLES = staticvariables;
			TDL tdl = new TDL();
			TDLMESSAGE tdlmessage = new TDLMESSAGE();
			REPORT report = new REPORT();
			report.NAME = "List of Stock Items";
			report.ISMODIFY = "No";
			report.ISFIXED = "No";
			report.ISINITIALIZE = "No";
			report.ISOPTION = "No";
			report.ISINTERNAL = "No";
			report.FORMS = "List of Stock Items";
			tdlmessage.REPORT = report;
			FORM form = new FORM();
			form.NAME = "List of Stock Items";
			form.ISMODIFY = "No";
			form.ISFIXED = "No";
			form.ISINITIALIZE = "No";
			form.ISOPTION = "No";
			form.ISINTERNAL = "No";
			form.TOPPARTS = "List of Stock Items";
			form.XMLTAG = "List of Stock Items";
			tdlmessage.FORM = form;
			PART part = new PART();
			part.NAME = "List of Stock Items";
			part.ISMODIFY = "No";
			part.ISFIXED = "No";
			part.ISINITIALIZE = "No";
			part.ISOPTION = "No";
			part.ISINTERNAL = "No";
			part.TOPLINES = "List of Stock Items";
			part.REPEAT = "List of Stock Items : Collection of Stock Items";
			part.SCROLLED = "Vertical";
			part.VERTICAL = "Yes";
			List<PART> parts = new List<PART>();
			parts.Add(part);
			tdlmessage.PART = parts;
			LINE line = new LINE();
			line.NAME = "List of Stock Items";

			line.ISMODIFY = "No";
			line.ISFIXED = "No";
			line.ISINITIALIZE = "No";
			line.ISOPTION = "No";
			line.ISINTERNAL = "No";
			line.XMLtag = "StockItem";
			// KEY MODIFICATION: Add FIELDS property to connect fields to the line
			line.FIELD = "Field StandardPrice,Field _Cess,Field _CentralTax,Name,Guid,Field Category,Field AlterID,Field Description,Field PartNo,Field Parent,Field FirstAlias,Field OpeningRate,Field IsBatchWiseOn,Field RateOfMrp,Field Denominator,Field Conversion,Field BaseUnits,Field RateOfVatField,Field Narration,Field LastSalePrice,Field _HSNCode,Field _IntegratedTax,Field _StateTax";
			List<LINE> lines = new List<LINE>();
			lines.Add(line);
			tdlmessage.LINE = lines;
			List<FIELD> fieldList = new List<FIELD>();
			FIELD field = new FIELD();
			field.NAME = "Name";
			field.ISMODIFY = "No";
			field.ISFIXED = "No";
			field.ISINITIALIZE = "No";
			field.ISOPTION = "No";

			field.ISINTERNAL = "No";
			field.SET = "$Name";
			field.XMLTAG = "NAME";
			fieldList.Add(field);
			FIELD field2 = new FIELD();
			field2.NAME = "Guid";
			field2.ISMODIFY = "No";
			field2.ISFIXED = "No";
			field2.ISINITIALIZE = "No";
			field2.ISOPTION = "No";
			field2.ISINTERNAL = "No";
			field2.SET = "$Guid";
			field2.XMLTAG = "GUID";
			fieldList.Add(field2);
            
            FIELD field4 = new FIELD();
            field4.NAME = "Field FirstAlias";
            field4.ISMODIFY = "No";
            field4.ISFIXED = "No";
            field4.ISINITIALIZE = "No";
            field4.ISOPTION = "No";
            field4.ISINTERNAL = "No";
            field4.SET = "$_FirstAlias";
            field4.XMLTAG = "FIRSTALIAS";
            fieldList.Add(field4);
            FIELD field5 = new FIELD();
            field5.NAME = "Field Parent";
            field5.ISMODIFY = "No";
            field5.ISFIXED = "No";
            field5.ISINITIALIZE = "No";
            field5.ISOPTION = "No";
            field5.ISINTERNAL = "No";
            field5.SET = "$Parent";
            field5.XMLTAG = "PARENT";
            fieldList.Add(field5);

            FIELD field6 = new FIELD();
            field6.NAME = "Field AlterID";
            field6.ISMODIFY = "No";
            field6.ISFIXED = "No";
            field6.ISINITIALIZE = "No";
            field6.ISOPTION = "No";
            field6.ISINTERNAL = "No";
            field6.SET = "$AlterID";
            field6.XMLTAG = "ALTERID";
            fieldList.Add(field6);
            FIELD field7 = new FIELD();
            field7.NAME = "Field Category";
            field7.ISMODIFY = "No";
            field7.ISFIXED = "No";
            field7.ISINITIALIZE = "No";
            field7.ISOPTION = "No";
            field7.ISINTERNAL = "No";
            field7.SET = "$Category";
            field7.XMLTAG = "CATEGORY";
            fieldList.Add(field7);
            FIELD field8 = new FIELD();
            field8.NAME = "Field RateOfMrp";
            field8.ISMODIFY = "No";
            field8.ISFIXED = "No";
            field8.ISINITIALIZE = "No";
            field8.ISOPTION = "No";
            field8.ISINTERNAL = "No";
            field8.SET = "$RateOfMrp";
            field8.XMLTAG = "RATEOFMRP";
            fieldList.Add(field8);
            FIELD field9 = new FIELD();
            field9.NAME = "Field OpeningRate";
            field9.ISMODIFY = "No";
            field9.ISFIXED = "No";
            field9.ISINITIALIZE = "No";
            field9.ISOPTION = "No";
            field9.ISINTERNAL = "No";
            field9.SET = "$OpeningRate";
            field9.XMLTAG = "OPENINGRATE";
            fieldList.Add(field9);
            FIELD field10 = new FIELD();
            field10.NAME = "Field RateOfVat";
            field10.ISMODIFY = "No";
            field10.ISFIXED = "No";
            field10.ISINITIALIZE = "No";
            field10.ISOPTION = "No";
            field10.ISINTERNAL = "No";
            field10.SET = "$RateOfVat";
            field10.XMLTAG = "RATEOFVAT";
            fieldList.Add(field10);
            FIELD field11 = new FIELD();
            field11.NAME = "Field BaseUnits";
            field11.ISMODIFY = "No";
            field11.ISFIXED = "No";
            field11.ISINITIALIZE = "No";
            field11.ISOPTION = "No";
            field11.ISINTERNAL = "No";
            field11.SET = "$BaseUnits";
            field11.XMLTAG = "BASEUNITS";
            fieldList.Add(field11);
            FIELD field12 = new FIELD();
            field12.NAME = "Field Conversion";
            field12.ISMODIFY = "No";
            field12.ISFIXED = "No";
            field12.ISINITIALIZE = "No";
            field12.ISOPTION = "No";
            field12.ISINTERNAL = "No";
            field12.SET = "$Conversion";
            field12.XMLTAG = "CONVERSION";
            fieldList.Add(field12);
            FIELD field13 = new FIELD();
            field13.NAME = "Field Denominator";
            field13.ISMODIFY = "No";
            field13.ISFIXED = "No";
            field13.ISINITIALIZE = "No";
            field13.ISOPTION = "No";
            field13.ISINTERNAL = "No";
            field13.SET = "$Denominator";
            field13.XMLTAG = "DENOMINATOR";
            fieldList.Add(field13);
            FIELD field14 = new FIELD();
            field14.NAME = "Field IsBatchWiseOn";
            field14.ISMODIFY = "No";
            field14.ISFIXED = "No";
            field14.ISINITIALIZE = "No";
            field14.ISOPTION = "No";
            field14.ISINTERNAL = "No";
            field14.SET = "$IsBatchWiseOn";
            field14.XMLTAG = "ISBATCHWISEON";
            fieldList.Add(field14);
            FIELD field15 = new FIELD();
            field15.NAME = "Field Narration";
            field15.ISMODIFY = "No";
            field15.ISFIXED = "No";
            field15.ISINITIALIZE = "No";
            field15.ISOPTION = "No";
            field15.ISINTERNAL = "No";
            field15.SET = "$Narration";
            field15.XMLTAG = "NARRATION";
            fieldList.Add(field15);
            FIELD field16 = new FIELD();
            field16.NAME = "Field PartNo";
            field16.ISMODIFY = "No";
            field16.ISFIXED = "No";
            field16.ISINITIALIZE = "No";
            field16.ISOPTION = "No";
            field16.ISINTERNAL = "No";
            field16.SET = "$PartNo";
            field16.XMLTAG = "PARTNUMBER";
            fieldList.Add(field16);
            FIELD field17 = new FIELD();
            field17.NAME = "Field ";
            field17.ISMODIFY = "No";
            field17.ISFIXED = "No";
            field17.ISINITIALIZE = "No";
            field17.ISOPTION = "No";
            field17.ISINTERNAL = "No";
            field17.SET = "$Description";
            field17.XMLTAG = "DESCRIPTION";
            fieldList.Add(field17);
            FIELD field18 = new FIELD();
            field18.NAME = "Field LastSalePrice";
            field18.ISMODIFY = "No";
            field18.ISFIXED = "No";
            field18.ISINITIALIZE = "No";
            field18.ISOPTION = "No";
            field18.ISINTERNAL = "No";
            field18.SET = "$_LastSalePrice";
            field18.XMLTAG = "LASTSALEPRICE";
            fieldList.Add(field18);
            FIELD field19 = new FIELD();
            field19.NAME = "Field _HSNCode";
            field19.ISMODIFY = "No";
            field19.ISFIXED = "No";
            field19.ISINITIALIZE = "No";
            field19.ISOPTION = "No";
            field19.ISINTERNAL = "No";
            field19.SET = "$_HSNCode";
            field19.XMLTAG = "HSNCODE";
            fieldList.Add(field19);
            FIELD field20 = new FIELD();
            field20.NAME = "Field _IntegratedTax";
            field20.ISMODIFY = "No";
            field20.ISFIXED = "No";
            field20.ISINITIALIZE = "No";
            field20.ISOPTION = "No";
            field20.ISINTERNAL = "No";
            field20.SET = "$_IntegratedTax";
            field20.XMLTAG = "INTEGRATEDTAX";
            fieldList.Add(field20);
            FIELD field21 = new FIELD();
            field21.NAME = "Field _StateTax";
            field21.ISMODIFY = "No";
            field21.ISFIXED = "No";
            field21.ISINITIALIZE = "No";
            field21.ISOPTION = "No";
            field21.ISINTERNAL = "No";
            field21.SET = "$_StateTax";
            field21.XMLTAG = "STATETAX";
            fieldList.Add(field21);
            FIELD field22 = new FIELD();
            field22.NAME = "Field _CentralTax";
            field22.ISMODIFY = "No";
            field22.ISFIXED = "No";
            field22.ISINITIALIZE = "No";
            field22.ISOPTION = "No";
            field22.ISINTERNAL = "No";
            field22.SET = "$_CentralTax";
            field22.XMLTAG = "CENTRALTAX";
            fieldList.Add(field22);
            FIELD field23 = new FIELD();
            field23.NAME = "Field _Cess";
            field23.ISMODIFY = "No";
            field23.ISFIXED = "No";
            field23.ISINITIALIZE = "No";
            field23.ISOPTION = "No";
            field23.ISINTERNAL = "No";
            field23.SET = "$_Cess";
            field23.XMLTAG = "CESS";
            fieldList.Add(field23);
            FIELD field24 = new FIELD();
            field24.NAME = "Field StandardPrice";
            field24.ISMODIFY = "No";
            field24.ISFIXED = "No";
            field24.ISINITIALIZE = "No";
            field24.ISOPTION = "No";
            field24.ISINTERNAL = "No";
            field24.SET = "$StandardPrice";
            field24.XMLTAG = "STANDARDPRICE";
            fieldList.Add(field24);
            tdlmessage.FIELD = fieldList;
			List<COLLECTION> collectionsList = new List<COLLECTION>();
			COLLECTION collection = new COLLECTION();
			collection.NAME = "Collection of Stock Items";
			collection.ISMODIFY = "No";
			collection.ISFIXED = "No";
			collection.ISINITIALIZE = "No";
			collection.ISOPTION = "No";
			collection.ISINTERNAL = "No";
			List<String> types = new List<String>();
			types.Add("Stock Item");
			collection.TYPE = types;
			List<String> fetch = new List<string>();
			fetch.Add("Name");
			fetch.Add("Guid");

			collection.FETCH = "StandardPrice,_Cess,_CentralTax,$_StateTax,Name,Guid,Category,AlterID,Parent,Description,PartNo,_FirstAlias,IsBatchWiseOn,OpeningRate,RateOfMrp,Denominator,Conversion,BaseUnits,RateOfVat,Narration,_LastSalePrice,_HSNCode,_IntegratedTax";
			collectionsList.Add(collection);
			tdlmessage.COLLECTION = collectionsList;
			tdl.TDLMESSAGE = tdlmessage;
			desc.TDL = tdl;
			body.DESC = desc;
			tallyRequest.BODY = body;
			return tallyRequest;
		}
	}
}
