using SNR_ClientApp.Properties;
using SNR_ClientApp.TallyResponses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace SNR_ClientApp.Tally.generateXml
{
	public static class GroupWiseGSTMaterGenerateXML
	{
		public static ENVELOPE groupwiseGstMasterGenerateXML()
		{
			ENVELOPE tallyRequest = new ENVELOPE();
			HEADER header = new HEADER();
			header.VERSION = "1";
			header.TALLYREQUEST = "Export";
			header.TYPE = "Data";
			header.ID = "List of Stock Groups";
			tallyRequest.HEADER = header;
			BODY body = new();
			DESC desc = new();
			STATICVARIABLES staticvariables = new STATICVARIABLES();
			staticvariables.EXPLODEFLAG = "Yes";
			staticvariables.SVCURRENTCOMPANY = ApplicationProperties.properties["tally.company"].ToString();
			staticvariables.SVEXPORTFORMAT = "$$SysName:XML";
			staticvariables.IsItemWise = "Yes";
			desc.STATICVARIABLES = staticvariables;
			TDL tdl = new TDL();
			TDLMESSAGE tdlmessage = new TDLMESSAGE();
			REPORT report = new REPORT();
			report.NAME = "List of Stock Groups";
			report.ISMODIFY = "No";
			report.ISFIXED = "No";
			report.ISINITIALIZE = "No";
			report.ISOPTION = "No";
			report.ISINTERNAL = "No";
			report.FORMS = "List of Stock Groups";
			tdlmessage.REPORT = report;
			FORM form = new FORM();
			form.NAME = "List of Stock Groups";
			form.ISMODIFY = "No";
			form.ISFIXED = "No";
			form.ISINITIALIZE = "No";
			form.ISOPTION = "No";
			form.ISINTERNAL = "No";
			form.TOPPARTS = "List of Stock Groups";
			form.XMLTAG = "List of Stock Groups";
			tdlmessage.FORM = form;
			PART part = new PART();
			part.NAME = "List of Stock Groups";
			part.ISMODIFY = "No";
			part.ISFIXED = "No";
			part.ISINITIALIZE = "No";
			part.ISOPTION = "No";
			part.ISINTERNAL = "No";
			part.TOPLINES = "Line Stock Groups";
			part.REPEAT = "Line Stock Groups : Collection of Stock Groups";
			part.SCROLLED = "Vertical";
			part.VERTICAL = "Yes";
			List<PART> parts = new List<PART>();
			parts.Add(part);
			tdlmessage.PART = parts;
			LINE line = new LINE();
			line.NAME = "Line Stock Groups";
			line.ISMODIFY = "No";
			line.ISFIXED = "No";
			line.ISINITIALIZE = "No";
			line.ISOPTION = "No";
			line.ISINTERNAL = "No";
			line.XMLtag = "STOCKGROUP";
			// KEY MODIFICATION: Add FIELDS property to connect fields to the line
			line.FIELD = "Field Name, Field Parent, Field Guid,Field alterid,Field RateOfVat,Field taxtype,Field gst_taxability,Field _HSNCode,Field _IntegratedTax,Field _CentralTax,Field _StateTax";

			List<LINE> lines = new List<LINE>();
			lines.Add(line);
			tdlmessage.LINE = lines;
			List<FIELD> fieldList = new List<FIELD>();
			FIELD field = new FIELD();
			field.NAME = "Field Name";
			field.ISMODIFY = "No";
			field.ISFIXED = "No";
			field.ISINITIALIZE = "No";
			field.ISOPTION = "No";
			field.ISINTERNAL = "No";
			field.SET = "$Name";
			field.XMLTAG = "NAME";
			fieldList.Add(field);
			FIELD field2 = new FIELD();
			field2.NAME = "Field Parent";
			field2.ISMODIFY = "No";
			field2.ISFIXED = "No";
			field2.ISINITIALIZE = "No";
			field2.ISOPTION = "No";
			field2.ISINTERNAL = "No";
			field2.SET = "$Parent";
			field2.XMLTAG = "PARENT";
			fieldList.Add(field2);
			FIELD field3 = new FIELD();
			field3.NAME = "Field Guid";
			field3.ISMODIFY = "No";
			field3.ISFIXED = "No";
			field3.ISINITIALIZE = "No";
			field3.ISOPTION = "No";
			field3.ISINTERNAL = "No";
			field3.SET = "$Guid";
			field3.XMLTAG = "GUID";
			fieldList.Add(field3);
			FIELD field4 = new FIELD();
			field4.NAME = "Field alterid";
			field4.ISMODIFY = "No";
			field4.ISFIXED = "No";
			field4.ISINITIALIZE = "No";
			field4.ISOPTION = "No";
			field4.ISINTERNAL = "No";
			field4.SET = "$alterid";
			field4.XMLTAG = "ALTERID";
			fieldList.Add(field4);
			FIELD field5 = new FIELD();
			field5.NAME = "Field RateOfVat";
			field5.ISMODIFY = "No";
			field5.ISFIXED = "No";
			field5.ISINITIALIZE = "No";
			field5.ISOPTION = "No";
			field5.ISINTERNAL = "No";
			field5.SET = "$RateOfVat";
			field5.XMLTAG = "RATEOFVAT";
			fieldList.Add(field5);
			FIELD field6 = new FIELD();
			field6.NAME = "Field taxtype";
			field6.ISMODIFY = "No";
			field6.ISFIXED = "No";
			field6.ISINITIALIZE = "No";
			field6.ISOPTION = "No";
			field6.ISINTERNAL = "No";
			field6.SET = "$taxtype";
			field6.XMLTAG = "TAXTYPE";
			fieldList.Add(field6);
			FIELD field7 = new FIELD();
			field7.NAME = "Field gst_taxability";
			field7.ISMODIFY = "No";
			field7.ISFIXED = "No";
			field7.ISINITIALIZE = "No";
			field7.ISOPTION = "No";
			field7.ISINTERNAL = "No";
			field7.SET = "$gst_taxability";
			field7.XMLTAG = "GSTTAXABLITY";
			fieldList.Add(field7);
			FIELD field8 = new FIELD();
			field8.NAME = "Field _HSNCode";
			field8.ISMODIFY = "No";
			field8.ISFIXED = "No";
			field8.ISINITIALIZE = "No";
			field8.ISOPTION = "No";
			field8.ISINTERNAL = "No";
			field8.SET = "$_HSNCode";
			field8.XMLTAG = "HSNCODE";
			fieldList.Add(field8);
			FIELD field9 = new FIELD();
			field9.NAME = "Field _IntegratedTax";
			field9.ISMODIFY = "No";
			field9.ISFIXED = "No";
			field9.ISINITIALIZE = "No";
			field9.ISOPTION = "No";
			field9.ISINTERNAL = "No";
			field9.SET = "$_IntegratedTax";
			field9.XMLTAG = "INTEGRATEDTAX";
			fieldList.Add(field9);
			FIELD field10 = new FIELD();
			field10.NAME = "Field _CentralTax";
			field10.ISMODIFY = "No";
			field10.ISFIXED = "No";
			field10.ISINITIALIZE = "No";
			field10.ISOPTION = "No";
			field10.ISINTERNAL = "No";
			field10.SET = "$_CentralTax";
			field10.XMLTAG = "CENTRALTAX";
			fieldList.Add(field10);
			FIELD field11 = new FIELD();
			field11.NAME = "Field _StateTax";
			field11.ISMODIFY = "No";
			field11.ISFIXED = "No";
			field11.ISINITIALIZE = "No";
			field11.ISOPTION = "No";
			field11.ISINTERNAL = "No";
			field11.SET = "$_StateTax";
			field11.XMLTAG = "STATETAX";
			fieldList.Add(field11);
	
			
			tdlmessage.FIELD = fieldList;

			List<COLLECTION> collectionsList = new List<COLLECTION>();
			COLLECTION collection = new COLLECTION();
			collection.NAME = "Collection of Stock Groups";
			collection.ISMODIFY = "No";
			collection.ISFIXED = "No";
			collection.ISINITIALIZE = "No";
			collection.ISOPTION = "No";
			collection.ISINTERNAL = "No";
			List<String> types = new List<String>();
			types.Add("Stock Group");
			collection.TYPE = types;
			// OPTIONAL MODIFICATION: Replace NativeMethod with FETCH for better compatibility
			List<String> fetch = new List<string>();
			fetch.Add("Name");
			fetch.Add("Parent");
			fetch.Add("Guid");
			fetch.Add("alterid");
			fetch.Add("$RateOfVat");
			collection.FETCH = "Name,Parent,Guid,alterid,$RateOfVat,taxtype,gst_taxability,gst_taxability,_HSNCode,_IntegratedTax,_CentralTax,_StateTax";
		

			collectionsList.Add(collection);

			tdlmessage.COLLECTION = collectionsList;
			tdl.TDLMESSAGE = tdlmessage;
			desc.TDL = tdl;
			body.DESC = desc;
			tallyRequest.BODY = body;
			return tallyRequest;
		}
	}
}
